"""Provider adapters and registry for travel data."""

from app.providers.registry import (
    ProviderRegistryConfig,
    ProviderRegistryError,
    TravelDataProviderRegistry,
    create_default_provider_registry,
    create_provider_registry,
    get_map_provider_order,
)
from app.providers.types import (
    GeocodeRequest,
    MapProvider,
    PlaceSearchRequest,
    ProviderAttemptFailure,
    ProviderError,
    ProviderHealth,
    ReverseGeocodeRequest,
    RouteRequest,
    SearchProvider,
    SearchRequest,
    SearchResult,
    SupplierProvider,
    SupplierReference,
    SupplierRequest,
    WeatherProvider,
    WeatherRequest,
    WeatherSummary,
)

__all__ = [
    "GeocodeRequest",
    "MapProvider",
    "PlaceSearchRequest",
    "ProviderAttemptFailure",
    "ProviderError",
    "ProviderHealth",
    "ProviderRegistryConfig",
    "ProviderRegistryError",
    "ReverseGeocodeRequest",
    "RouteRequest",
    "SearchProvider",
    "SearchRequest",
    "SearchResult",
    "SupplierProvider",
    "SupplierReference",
    "SupplierRequest",
    "TravelDataProviderRegistry",
    "WeatherProvider",
    "WeatherRequest",
    "WeatherSummary",
    "create_default_provider_registry",
    "create_provider_registry",
    "get_map_provider_order",
]
