import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, "../..")
const schemaPath = path.join(repoRoot, "api/dist/schema.json")
const outputPath = path.join(repoRoot, "web/src/lib/generated/types.ts")

const schema = JSON.parse(await readFile(schemaPath, "utf-8"))
const defs = schema.$defs ?? {}
const names = Object.keys(defs).sort()

function refName(ref) {
  return ref.replace("#/$defs/", "")
}

function literal(value) {
  return JSON.stringify(value)
}

function compile(schemaNode) {
  if (!schemaNode || typeof schemaNode !== "object") return "unknown"
  if (schemaNode.$ref) return refName(schemaNode.$ref)
  if (Array.isArray(schemaNode.enum)) return schemaNode.enum.map(literal).join(" | ")
  if (schemaNode.const !== undefined) return literal(schemaNode.const)
  if (Array.isArray(schemaNode.anyOf)) return compileUnion(schemaNode.anyOf)
  if (Array.isArray(schemaNode.oneOf)) return compileUnion(schemaNode.oneOf)

  if (schemaNode.type === "array") return `${compile(schemaNode.items)}[]`
  if (schemaNode.type === "integer" || schemaNode.type === "number") return "number"
  if (schemaNode.type === "string") return "string"
  if (schemaNode.type === "boolean") return "boolean"
  if (schemaNode.type === "null") return "null"
  if (schemaNode.type === "object") {
    if (schemaNode.additionalProperties && typeof schemaNode.additionalProperties === "object") {
      return `Record<string, ${compile(schemaNode.additionalProperties)}>`
    }
    if (schemaNode.additionalProperties === true || !schemaNode.properties) {
      return "Record<string, unknown>"
    }
    return compileInlineObject(schemaNode)
  }

  return "unknown"
}

function compileUnion(items) {
  return Array.from(new Set(items.map(compile))).join(" | ")
}

function propertyName(name) {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name)
}

function compileInlineObject(schemaNode) {
  const required = new Set(schemaNode.required ?? [])
  const lines = Object.entries(schemaNode.properties ?? {}).map(([name, prop]) => {
    const optional = required.has(name) ? "" : "?"
    return `  ${propertyName(name)}${optional}: ${compile(prop)}`
  })
  return `{\n${lines.join("\n")}\n}`
}

function emitDefinition(name, schemaNode) {
  if (schemaNode.type === "object" && schemaNode.properties) {
    return `export interface ${name} ${compileInlineObject(schemaNode)}`
  }
  return `export type ${name} = ${compile(schemaNode)}`
}

const content = [
  "// Generated by web/scripts/generate-types.mjs from api/dist/schema.json.",
  "// Do not edit manually.",
  "",
  ...names.map((name) => emitDefinition(name, defs[name])),
].join("\n\n") + "\n"

await mkdir(path.dirname(outputPath), { recursive: true })
await writeFile(outputPath, content, "utf-8")
